sudo: required
language: node_js

node_js:
  - 'stable'

cache:
  directories:
    - node_modules

env:
  - global:
      - NODE_ENV = test
      - CC_TEST_REPORTER_ID=2325634b95753b3bb9c2d5d4e0b7739f75f3480d6b3bdb1b122e557c4133740b

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
